export const payerBillRates = [
  {
    agencyName: 'Louisiana Labor of  Love',
    serviceDescription: 'COTA - Hourly',
    billingDescription: 'COTA Hourly',
    unitOfMeasure: 'Hourly',
    allowOverride: true,
    payerRate: 30,
    chargeAmount: 0,
    revenueCode: 432,
    billingCodes: 'G0158',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
  {
    agencyName: 'Louisiana Labor of  Love',
    serviceDescription: 'COTA - Visit',
    billingDescription: 'COTA Visit',
    unitOfMeasure: 'Per Visit',
    allowOverride: false,
    payerRate: 30,
    chargeAmount: 145,
    revenueCode: 431,
    billingCodes: 'G0158',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
  {
    agencyName: 'Louisiana Labor of  Love',
    serviceDescription: 'HHA - Visit',
    billingDescription: 'HHA Visit',
    unitOfMeasure: 'Per Visit',
    allowOverride: false,
    payerRate: 0,
    chargeAmount: 65,
    revenueCode: 571,
    billingCodes: 'G0156',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
  {
    agencyName: 'Louisiana Labor of  Love',
    serviceDescription: 'Hospice LPN - Post-Mortem Visit',
    billingDescription: 'Hospice LPN Post-Mortem',
    unitOfMeasure: '15 Minute Increment',
    allowOverride: true,
    payerRate: 95,
    chargeAmount: 75,
    revenueCode: 551,
    billingCodes: 'G0300 PM',
    startDate: new Date().toLocaleDateString(),
    endDate: '12/32/2021',
  },
  {
    agencyName: 'Louisiana Labor of  Love',
    serviceDescription: 'Hospice LPN - Post-Mortem Visit',
    billingDescription: 'Hospice LPN Post-Mortem',
    unitOfMeasure: '15 Minute Increment',
    allowOverride: true,
    payerRate: 0,
    chargeAmount: 75,
    revenueCode: 432,
    billingCodes: 'G0300 PM',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
];

export const payerCBRData = [
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'O-97755 Assistive Technology',
    description: 'Assistive Technology',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '9775',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
  {
    service: 'P-97113 Aquatic Therapy',
    description: 'Aquatic Therapy/Exercise',
    unitOfMeasure: '15 Minute Increment',
    HCPCCode: '97113',
  },
];

export const payerRules = [
  {
    name: 'Print Time InOut',
    description: 'Print time In/Out',
    groupCode: 'Generic',
    isActive: false,
    isVisible: true,
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
  {
    name: 'Charge Rate',
    description: 'Set Charge rate to payer Rate',
    groupCode: 'Rates',
    isActive: false,
    isVisible: true,
    startDate: new Date().toLocaleDateString(),
    endDate: '',
  },
];

export const payerEncountersData = [
  {
    patient: 'McNaughton James',
    status: 'Active',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
    dischargeDate: '',
    encounterPayerStatus: 'Active',
    sequence: 1,
    differences: 'Service Requirement',
  },
  {
    patient: 'McNaughton James',
    status: 'Active',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
    dischargeDate: '',
    encounterPayerStatus: 'Active',
    sequence: 1,
    differences: 'Service Requirement, Miscellaneous Billing Required',
  },
  {
    patient: 'Pitts Coyle',
    status: 'Active',
    startDate: new Date().toLocaleDateString(),
    endDate: '',
    dischargeDate: '',
    encounterPayerStatus: 'Active',
    sequence: 1,
    differences:
      'Service Requirement, Copay Type Code, Miscellaneous Billing Required',
  },
];

export const payerFormData = [
  {
    type: '60 Day Summary',
    created: new Date().toLocaleDateString(),
    performedBy: 'Peggy Oppong',
    revisedBy: 'Nick Dadzie',
    status: 'Incomplete',
  },
  {
    type: 'Infection Control Form',
    created: new Date().toLocaleDateString(),
    performedBy: 'Peggy Oppong',
    revisedBy: 'Nick Dadzie',
    status: 'Completed',
  },
  {
    type: '60 Day Summary',
    created: new Date().toLocaleDateString(),
    performedBy: 'Peggy Oppong',
    revisedBy: 'Nick Dadzie',
    status: 'Incomplete',
  },
];
