export const serviceCat = [
  'Skilled Nurse',
  'Physical Therapist',
  'Occupational Therapist',
  'Speech Therapist',
  'Social Worker',
  'Home Health Aide',
  'Chore Services',
  'Comprehensive',
  'Homemaker',
  'Other Paraprofessional',
  'Personal Care',
  'Respite',
  'Supplies',
  'Durable Medical Equipment',
  'Pharmaceutical Lab Services',
  'Level of Care',
  'Supervisory Visit - Aide',
  'Supervisory Visit - LPN',
  'Supervisory Visit - OT',
  'Supervisory Visit - PT',
  'Pay Only',
  'Modalities',
  'Other Professional',
];

export const payerReportingGroup = [
  'Medicare',
  'Medicare Part A',
  'Medicare Part A',
  'Medicare Hospice',
  'Medicare Outpatient',
  'Medicaid',
  'Waiver',
  'Insurance',
  'BC/BS',
  'Contractual',
  'Staffing',
  'Private Pay',
  'Third Party',
  'Workers Compensation',
  'Charity',
  'Unknown',
];

export const days = [
  'Today',
  'Yesterday',
  'This Week',
  'This Month',
  'This Year',
  'Year To Date',
  'Last Week',
  'Last Month',
];
