export const employmentReq = [
  {
    item: '2 forms of identification',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: false,
    completed: '',
    renewal: '',
  },
  {
    item: '2 referance verification',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: false,
    completed: new Date().toLocaleDateString(),
    renewal: '',
  },
  {
    item: 'Background Check',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Peggy',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Consumer Affairs',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: '',
    completed: '',
    renewal: '',
  },
  {
    item: 'Employee Handbook',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Destiny',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Employment Verification Authorization',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Jerry',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Evaluation Date',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Joseph',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'HIPAA Class',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Nicholas',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: false,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: '19 Renewal Date',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: '19 Renewal Date',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Interview Questionary',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: false,
    completed: '',
    renewal: '',
  },
  {
    item: 'Job Description',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Liability Insurance',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: false,
    completed: '',
    renewal: '',
  },
  {
    item: 'OSHA',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: false,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Resume',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
];

export const associateAddFormData = [
  '90 Day Eval',
  'Auto Insurance Coverage Verification',
  'Automobile Insurance Verification Form',
  'Baseline TB Screening Tool for Heath Care Workers',
  'Conflict of Interest',
  'CORONAVIRUS SCREENING QUESTIONNAIRE (EMPLOYEE)(v2)',
  'Direct Deposit',
  'Drug Testing Consent Form',
  'Electronic Documentation & Signature authenticity',
  'Employee Confidentiality Non-Disclosure Agreement',
  'Employee Grievance Form',
  'Employee Wage Notice',
  "Employee's Withholding Exemption Certificate",
  'Hepatitis B / Flu Vaccine Screening Form',
  'Mantous Tuberculin (TB) Skin Test Record',
  'MVR Authorization Form',
];
