export const medicalReq = [
  {
    item: 'COVID 19',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: false,
    completed: '',
    renewal: '',
  },
  {
    item: 'Hepatitis B',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: false,
    completed: new Date().toLocaleDateString(),
    renewal: '',
  },
  {
    item: 'Measless/Mups',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Peggy',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Physical Exam',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: '',
    lastModifiedByDate: '',
    comment: '',
    complaint: '',
    completed: '',
    renewal: '',
  },
  {
    item: 'Quantiferon Gold Test',
    hasResult: true,
    hasCompleted: true,
    hasRenewal: false,
    lastModifiedBy: 'Destiny',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Rubella',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Jerry',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Rubeola',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Joseph',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'T-dap',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Nicholas',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: false,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Tuberculine Skin Test ',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
  {
    item: 'Varicella',
    hasResult: false,
    hasCompleted: false,
    hasRenewal: true,
    lastModifiedBy: 'Guest',
    lastModifiedByDate: new Date().toLocaleDateString(),
    comment: 'Hello World',
    complaint: true,
    completed: new Date().toLocaleDateString(),
    renewal: new Date().toLocaleDateString(),
  },
];

export const evvVisitData = [
  {
    date: `${new Date().toLocaleString()}-${
      new Date().toUTCString().split(' ')[5]
    }  `,
    type: 'Start Care',

    note: 'Jessie James (Personal Care Aide - Hourly) 846 12th St SW, Huron, SD 57350, USA',
  },
  {
    date: `${new Date().toLocaleString()}-${
      new Date().toUTCString().split(' ')[5]
    }  `,
    type: 'Start Care',

    note: 'Jessie James (Personal Care Aide - Hourly) 1225 Minnesota Ave SW, Huron, SD 57350, USA',
  },
  {
    date: `${new Date().toLocaleString()}-${
      new Date().toUTCString().split(' ')[5]
    }  `,
    type: 'Start Care',

    note: 'Jessie James (Personal Care Aide - Hourly) 1225 Minnesota Ave SW, Huron, SD 57350, USA',
  },
];

export const employmentDiscipline = [
  'Registered Nurse',
  'Licensed Practical/Vocational Nurse',
  'Physical Therapist',
  'Physical Therapist Assistant',
  'Occupational Therapist',
  'Certified Occupational Therapist Assistant',
  'Speech Therapist',
  'Speech Therapist Assistant',
  'Social Worker',
  'Bachelor of Social Worker',
  'Home Health Aide',
  'Other Paraprofessional',
  'Supervisory Visit - Aide',
  'Supervisory Visit - LPN',
  'Supervisory Visit - OT',
  'Supervisory Visit - PT',
  'Chore Worker',
  'Comprehensive',
  'HomeMaker',
  'Personal Care',
  'Respite',
];
